using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.DataAccess.Sql;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
using MySql.Data.MySqlClient;

namespace officeManager
{
    public partial class memSearchPopupForm : DevExpress.XtraEditors.XtraForm
    {

        private MySqlConnection _DB_MYSQL_CONNECT = null;
        MemberRegForm _parent = null;
        string query = null;

        public void conn_DB_MYSQL_CONNECT_open()
        {
            try
            {
                if (_DB_MYSQL_CONNECT != null)
                    _DB_MYSQL_CONNECT.Close();

                _DB_MYSQL_CONNECT = new MySqlConnection(officeMainForm.mySQL_ConnString);
                _DB_MYSQL_CONNECT.Open();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "DB Open Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        public void conn_DB_MYSQL_CONNECT_close()
        {
            _DB_MYSQL_CONNECT.Close();
        }

        public memSearchPopupForm(string name,MemberRegForm parent )
        {
            InitializeComponent();
            textEditAddr.Text = name;
            simpleButtonQuery_Click(null, null);
            _parent = parent;
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            //sqlDataSource1.Fill();
        }

        private void simpleButtonQuery_Click(object sender, EventArgs e)
        {
            if (textEditAddr.Text.Trim() == null || textEditAddr.Text.Trim() == "" || textEditAddr.Text.Trim() == " ")
            {
                MessageBox.Show("조회하고자 하는 지명 또는 건물을 입력하시기 바랍니다.");
                textEditAddr.Focus();
                return;
            }

            conn_DB_MYSQL_CONNECT_open();

            try
            {
                DataTable table = new DataTable();

                for (int i = 0; i < gridViewAddrSearch.Columns.Count; i++)
                {
                    DevExpress.XtraGrid.Columns.GridColumn column = gridViewAddrSearch.Columns[i];
                    if (column.FieldName == "ORD_SEQ")
                    {
                        table.Columns.Add(column.FieldName, typeof(decimal));
                    }
                    else
                    {
                        table.Columns.Add(column.FieldName, typeof(string));
                    }
                }

                // Select Query
                query =
                    "SELECT MBR_NO             " +
                    "     , APPLY_SEQ               " +
                    "     , MBR_NM            " +
                    "     , GENDER          " +
                    "     , SUBJ_CD       " +
                    "     , LVL_CD        " +
                    "     , CNTR_FG_CD " +
                    "     , SUBS_AMT     " +
                    "     , SUBS_MM_CNT          " +
                    "     , MBR_FG_CD            " +
                    "     , CTRTR_NM       " +
                    "     , MBR_REL_NM        " +
                    "     , PHON_NO        " +
                    "  FROM MBR_SUBJ_APPLY            " +
                    " WHERE MBR_NM          LIKE '" + textEditAddr.Text.Trim().ToString() + "%'" +
                    "   AND SUBSTR(MBR_NO,1,4) = '" + officeMainForm.main_BrchCd.Trim().ToString() + "'" +

                    " ORDER BY MBR_NM, MBR_NO, APPLY_SEQ ";

                MySqlCommand command = new MySqlCommand(query, _DB_MYSQL_CONNECT);//officeMainForm.main_BrchCd

                MySqlDataReader reader = command.ExecuteReader();

                while (reader.Read())
                {
                    DataRow row = table.NewRow();
                    for (int i = 0; i < reader.FieldCount; i++)
                    {
                        row[i] = reader.GetValue(i);
                        //row[i] = i;
                    }

                    table.Rows.Add(row);
                }

                reader.Close();   // 쿼리문 결과 닫기, Reader 로 열었으면 반드시 닫아야 한다.
                conn_DB_MYSQL_CONNECT_close();  // Connection Close     

                gridControlMemSearch.DataSource = table;
               
                //gridViewCommCdMaster.BestFitColumns();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }

        }

        private void textEditAddr_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (e.KeyChar == '\r')
            {
                simpleButtonQuery_Click(sender, e);
            }
        }

        private void gridControlAddrSearch_DoubleClick(object sender, EventArgs e)
        {


            MouseEventArgs ea = e as MouseEventArgs;
            if (ea == null) return;
            GridHitInfo hi = gridViewAddrSearch.CalcHitInfo(ea.Location);
            int datasourceRowIndex = gridViewAddrSearch.GetDataSourceRowIndex(hi.RowHandle);
         
            int rowHandle = gridViewAddrSearch.GetRowHandle(datasourceRowIndex);

            //gridViewCommCdMaster.AddNewRow();
            //MessageBox.Show(rowHandle.ToString());
            if (rowHandle >= 0)
            {
                string memid = gridViewAddrSearch.GetRowCellValue(rowHandle, "MBR_NO").ToString();
                string seq = gridViewAddrSearch.GetRowCellValue(rowHandle, "APPLY_SEQ").ToString();
                _parent.getMember(memid, seq);
                this.Close();

                //Dispose();
            }
        }

  
    }
}